In [82]:
import json
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Need to inlcude the statement below before importing pandas_datareader if your version of pandas is the most recent 0.23.0
pd.core.common.is_list_like = pd.api.types.is_list_like

from pandas_datareader import data, wb

In [60]:
tickers = ['DBX', 'DOCU']

In [61]:
prices_df = pd.DataFrame()
for ticker in tickers:
        temp_df = data.DataReader(str(ticker), 'morningstar', '2018-01-01', '2018-06-28')
        prices_df = prices_df.append(temp_df)

In [62]:
prices_df = prices_df.reset_index(level=[0,1])
prices_df.head()

  Symbol       Date  Close     High    Low   Open    Volume
0    DBX 2018-03-23  28.48  31.6000  27.84  29.00  56108660
1    DBX 2018-03-26  30.45  30.6600  27.75  30.45  16985727
2    DBX 2018-03-27  29.90  30.6800  29.00  30.41   6910962
3    DBX 2018-03-28  30.98  31.1900  28.61  29.26   5113289
4    DBX 2018-03-29  31.25  34.3667  30.79  31.98  15800189

In [65]:
ipodata_df = pd.read_excel('../capstone/data/SCOOP-Rating-Performance.xls', 'SCOOP Scorecard', usecol=11, skiprows=36)
ipodata_df.columns=['Date', 'Issuer', 'Symbol', 'Managers', 'Offer Price', 'Open Price', '1st Day Close','1st Day % Px Chng', '$ Change Opening', '$ Change Close', 'Ratings','Performed'
]
ipodata_df = ipodata_df.set_index('Symbol')
ipodata_df.head()

,Date,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Ratings,Performed
Symbol,,,,,,,,,,,
ILPT,2018-01-12 00:00:00,Industrial Logistics Properties Trust,UBS Investment Bank/ Citigroup/ RBC Capital Ma...,24,23.7,23.35,-0.0270833,-0.3,-0.65,1,NaN
LBRT,2018-01-12 00:00:00,Liberty Oilfield Services,"Morgan Stanley/ Goldman, Sachs/ Wells Fargo Se...",17,21.2,21.75,0.279412,4.2,4.75,2,NaN
EAGLU,2018-01-12 00:00:00,Platinum Eagle Acquisition,Deutsche Bank Securities/ BofA Merrill Lynch,10,10.06,10.01,0.001,0.06,0.01,1,NaN
PAGS,2018-01-24 00:00:00,PagSeguro Digital Ltd.,Goldman Sachs/ Morgan Stanley,21.5,28.2,29.2,0.35814,6.7,7.7,3,NaN
EYEN,2018-01-25 00:00:00,Eyenovia,Ladenburg Thalmann/ Roth Capital Partners​,10,10,9.92,-0.008,0,-0.08,1,NaN

In [66]:
ipo_info = ipodata_df.loc[tickers]
ipo_info

,Date,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Ratings,Performed
Symbol,,,,,,,,,,,
DBX,2018-03-23 00:00:00,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48,3,NaN
DOCU,2018-04-27 00:00:00,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73,3,NaN

In [67]:
ipo_info = ipo_info.rename(columns={'Symbol': 'Ticker', 'Date': 'Offer Date'})
ipo_info['Offer Date'] = pd.to_datetime(ipo_info['Offer Date'])
ipo_info.drop(['Performed'], axis=1, inplace=True)
ipo_info.drop(['Ratings'], axis=1, inplace=True)
ipo_info

,Offer Date,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close
Symbol,,,,,,,,,
DBX,2018-03-23,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48
DOCU,2018-04-27,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73

In [68]:
ipo_df

,Date,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Ratings,Performed
Symbol,,,,,,,,,,,
DBX,2018-03-23 00:00:00,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48,3,NaN
DOCU,2018-04-27 00:00:00,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73,3,NaN

In [69]:
ipo_info['Offer Date +90'] = ipo_info['Offer Date'] + timedelta(days=90)
ipo_info.to_csv('NEW_IPO_INFO.csv')
ipo_info

,Offer Date,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Offer Date +90
Symbol,,,,,,,,,,
DBX,2018-03-23,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48,2018-06-21
DOCU,2018-04-27,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73,2018-07-26

In [70]:
ipo_info['Offer Date +90'].replace(to_replace=pd.to_datetime('2018-07-26'), value=pd.to_datetime('2018-06-28'), inplace=True)

In [71]:
#prices_df = prices_df.rename(columns={'Symbol': 'Ticker'})
ipo_info = pd.merge(ipo_info,
                       prices_df[['Date', 'Symbol', 'Close']],
                       left_on = ['Offer Date +90', 'Symbol'],
                       right_on = ['Date', 'Symbol'],
                       how='left')

In [72]:
ipo_info

,Offer Date,Symbol,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Offer Date +90,Date,Close
0,2018-03-23,DBX,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48,2018-06-21,2018-06-21,35.69
1,2018-04-27,DOCU,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73,2018-06-28,2018-06-28,53.04

In [73]:
ipo_info = ipo_info.rename(columns={'Close': 'Close +90'})
ipo_info['% Px Chng +90'] = (ipo_info['Close +90'] - ipo_info['1st Day Close'])/ipo_info['1st Day Close']
ipo_info['Label'] = ''

In [74]:
for i in range(0, len(ipo_info)):
    if ipo_info['% Px Chng +90'][i] < -0.02:
        ipo_info['Label'][i] = 'Negative'
    elif ipo_info['% Px Chng +90'][i] > 0.02:
        ipo_info['Label'][i] = 'Positive'
    else:
        ipo_info['Label'][i] = 'Neutral'

/home/mji/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [75]:
ipo_info

,Offer Date,Symbol,Issuer,Managers,Offer Price,Open Price,1st Day Close,1st Day % Px Chng,$ Change Opening,$ Change Close,Offer Date +90,Date,Close +90,% Px Chng +90,Label
0,2018-03-23,DBX,Dropbox,Goldman Sachs/ J.P. Morgan/ Deutsche Bank Secu...,21,29,28.48,0.35619,8,7.48,2018-06-21,2018-06-21,35.69,0.25316,Positive
1,2018-04-27,DOCU,DocuSign,Morgan Stanley/ J.P. Morgan,29,38,39.73,0.37,9,10.73,2018-06-28,2018-06-28,53.04,0.335011,Positive

In [76]:
headlines = pd.read_csv('Test Data.csv')
headlines.head()

,Headline,Source,Date,Word Count,Company
0,*Docusign Files for IPO,Dow Jones Institutional News,3/28/18,109,Docusign
1,*DocuSign Inc. IPO Offering 16M Shares at $24-...,Dow Jones Institutional News,4/17/18,27,Docusign
2,*DocuSign Now Sees 16M-Share IPO Pricing at $2...,Dow Jones Institutional News,4/25/18,71,Docusign
3,*DocuSign Updates IPO Filing,Dow Jones Institutional News,4/3/18,60,Docusign
4,*DropBox Inc. Files for IPO,Dow Jones Institutional News,2/23/18,35,Dropbox

In [77]:
company_ticker = {'Dropbox': 'DBX', 'Docusign': 'DOC'}
headlines['Symbol'] = headlines['Company'].map(company_ticker)
headlines.head()

,Headline,Source,Date,Word Count,Company,Symbol
0,*Docusign Files for IPO,Dow Jones Institutional News,3/28/18,109,Docusign,DOC
1,*DocuSign Inc. IPO Offering 16M Shares at $24-...,Dow Jones Institutional News,4/17/18,27,Docusign,DOC
2,*DocuSign Now Sees 16M-Share IPO Pricing at $2...,Dow Jones Institutional News,4/25/18,71,Docusign,DOC
3,*DocuSign Updates IPO Filing,Dow Jones Institutional News,4/3/18,60,Docusign,DOC
4,*DropBox Inc. Files for IPO,Dow Jones Institutional News,2/23/18,35,Dropbox,DBX

In [83]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font_scale=1.5)
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import text

In [136]:
headlines = headlines.rename(columns={'Symbol': 'Ticker'})
ipo_info = ipo_info.rename(columns={'Symbol': 'Ticker'})

In [153]:
new_text_data = headlines['Headline'].replace('\d+', 'NUM_', regex=True)
new_text_data.to_csv('new_text_data.csv')

In [84]:
my_stop_words = ('dropbox', 'docusign', 'num_', 'ipo', 'negative', 'neutral', 'positive')
stop_words = text.ENGLISH_STOP_WORDS.union(my_stop_words)

In [85]:
vectorizer = CountVectorizer(analyzer='word', stop_words=stop_words)

In [86]:
vectorizer.fit(text_data)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None,
        stop_words=frozenset({'that', 'except', 'him', 'itself', 'part', 'further', 'before', 'mostly', 'through', 'next', 'had', 'what', 'beside', 'latterly', 'in', 'toward', 'though', 'who', 'former', 'nor', 'very', 'out', 'twenty', 'made', 'anyway', 'nevertheless', 'amoungst', 'sixty', 'enough', 'done', ...eg', 'the', 'below', 'ie', 'to', 'therein', 'became', 'thereupon', 'two', 'me', 'whether', 'after'}),
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [87]:
vectorizer.get_feature_names()

['aaron',
 'access',
 'according',
 'action',
 'actions',
 'advance',
 'affect',
 'ago',
 'ahead',
 'aiming',
 'aims',
 'alibaba',
 'alongside',
 'amid',
 'analysts',
 'announce',
 'announces',
 'annual',
 'anticipated',
 'ap',
 'apiece',
 'applies',
 'area',
 'arrive',
 'arriving',
 'article',
 'aside',
 'asks',
 'attractive',
 'automate',
 'avoid',
 'avoids',
 'awaited',
 'baidu',
 'banking',
 'barron',
 'barrons',
 'based',
 'bay',
 'beat',
 'beats',
 'beautiful',
 'bell',
 'bellwether',
 'best',
 'big',
 'biggest',
 'billion',
 'biotech',
 'biotechnology',
 'block',
 'blockbuster',
 'blockchain',
 'blog',
 'bloomberg',
 'bodes',
 'bono',
 'book',
 'boosted',
 'boosts',
 'boring',
 'boss',
 'box',
 'breakingviews',
 'breakouts',
 'brief',
 'broadcom',
 'bullish',
 'business',
 'buy',
 'buying',
 'buzz',
 'canada',
 'capital',
 'capture',
 'cash',
 'celebration',
 'center',
 'ceo',
 'ceridian',
 'chief',
 'citing',
 'class',
 'close',
 'closed',
 'closely',
 'closes',
 'cloud',
 'cnbc',
 'collaboration',
 'colorful',
 'com',
 'combinator',
 'come',
 'comes',
 'common',
 'companies',
 'company',
 'comparison',
 'competition',
 'conference',
 'confidential',
 'confidentially',
 'consider',
 'consumers',
 'continues',
 'contracts',
 'controversy',
 'corporate',
 'corrected',
 'costco',
 'couldn',
 'countries',
 'course',
 'court',
 'coverage',
 'customers',
 'da',
 'daily',
 'data',
 'davidson',
 'day',
 'dbx',
 'deal',
 'debut',
 'debuts',
 'decline',
 'defies',
 'demand',
 'derived',
 'details',
 'digits',
 'dips',
 'disappoints',
 'discloses',
 'docu',
 'document',
 'documents',
 'does',
 'doesn',
 'doj',
 'dollar',
 'dollars',
 'double',
 'earlier',
 'early',
 'earnings',
 'edt',
 'education',
 'electronic',
 'elite',
 'embraces',
 'end',
 'estimates',
 'exclusive',
 'executives',
 'exhales',
 'expectations',
 'expected',
 'expects',
 'explores',
 'extra',
 'eyes',
 'facebook',
 'fail',
 'falls',
 'familiar',
 'fang',
 'far',
 'fever',
 'file',
 'filed',
 'files',
 'filing',
 'final',
 'finance',
 'finishes',
 'firm',
 'firms',
 'follow',
 'following',
 'founders',
 'francisco',
 'friday',
 'friends',
 'frothy',
 'fuel',
 'funded',
 'funding',
 'future',
 'gains',
 'gave',
 'gets',
 'getting',
 'giddy',
 'gives',
 'global',
 'going',
 'goldman',
 'good',
 'goose',
 'governance',
 'grab',
 'gravity',
 'great',
 'greatly',
 'green',
 'growing',
 'growth',
 'gsv',
 'headline',
 'heads',
 'hearing',
 'help',
 'helped',
 'high',
 'higher',
 'hire',
 'hires',
 'hits',
 'hold',
 'hopes',
 'hot',
 'hours',
 'icymi',
 'idea',
 'increases',
 'indicated',
 'information',
 'initial',
 'initiate',
 'insiders',
 'investing',
 'investment',
 'investors',
 'invests',
 'ipos',
 'iqiyi',
 'ire',
 'isn',
 'issue',
 'item',
 'jmp',
 'join',
 'jpmorgan',
 'judge',
 'jump',
 'jumps',
 'just',
 'know',
 'korea',
 'largest',
 'latest',
 'launch',
 'launched',
 'launches',
 'launching',
 'lead',
 'leader',
 'leap',
 'lessons',
 'levie',
 'lifts',
 'like',
 'list',
 'listing',
 'little',
 'lives',
 'long',
 'look',
 'looks',
 'looming',
 'looms',
 'losses',
 'low',
 'lower',
 'lures',
 'lyft',
 'major',
 'make',
 'makes',
 'march',
 'mark',
 'market',
 'marketwatch',
 'marking',
 'matter',
 'maybe',
 'mean',
 'media',
 'microsoft',
 'million',
 'mistakes',
 'mln',
 'mn',
 'morning',
 'multi',
 'multiples',
 'names',
 'nasdaq',
 'near',
 'nearly',
 'need',
 'netflix',
 'new',
 'newcomer',
 'news',
 'niche',
 'nlight',
 'north',
 'nra',
 'num_b',
 'num_bn',
 'num_docusign',
 'num_dropbox',
 'num_m',
 'num_mn',
 'num_st',
 'num_the',
 'num_x',
 'nyse',
 'offering',
 'offerings',
 'officially',
 'old',
 'open',
 'opening',
 'opens',
 'opinion',
 'option',
 'orders',
 'overseas',
 'oversubscribed',
 'owns',
 'pact',
 'palatable',
 'pares',
 'partnerships',
 'paused',
 'paying',
 'pct',
 'peak',
 'peers',
 'percent',
 'period',
 'phase',
 'pile',
 'pitch',
 'pitches',
 'pitching',
 'plan',
 'planner',
 'planning',
 'plans',
 'point',
 'points',
 'pop',
 'pops',
 'position',
 'possible',
 'post',
 'pre',
 'prepare',
 'prepares',
 'preparing',
 'preps',
 'presents',
 'preview',
 'previously',
 'price',
 'priced',
 'prices',
 'pricing',
 'private',
 'privately',
 'proceeds',
 'profit',
 'provider',
 'public',
 'publicly',
 'pull',
 'push',
 'puts',
 'quiet',
 'quietly',
 'quotation',
 'quotes',
 'raise',
 'raised',
 'raises',
 'range',
 'rangs',
 'ranks',
 'recent',
 'refile',
 'released',
 'report',
 'reportedly',
 'reports',
 'reportsdropbox',
 'represents',
 'results',
 'return',
 'reuters',
 'revenue',
 'review',
 'revises',
 'rich',
 'ring',
 'roadshow',
 'rowe',
 'runners',
 'said',
 'sales',
 'salesforce',
 'san',
 'sanctions',
 'say',
 'says',
 'saysas',
 'saysin',
 'scale',
 'search',
 'seattle',
 'sec',
 'secret',
 'seeking',
 'seeks',
 'seen',
 'sees',
 'sell',
 'sells',
 'set',
 'sets',
 'setting',
 'shape',
 'share',
 'shares',
 'sharing',
 'shift',
 'shoe',
 'short',
 'shows',
 'shr',
 'shrinking',
 'shrs',
 'shy',
 'sights',
 'signals',
 'signature',
 'silicon',
 'simpson',
 'slightly',
 'smart',
 'smartsheet',
 'smiles',
 'snap',
 'soar',
 'soars',
 'software',
 'sohn',
 'sold',
 'somewhat',
 'source',
 'sources',
 'spotify',
 'spotlight',
 'square',
 'stacks',
 'stage',
 'stake',
 'stands',
 'starbucks',
 'start',
 'started',
 'startups',
 'states',
 'stock',
 'stocks',
 'storage',
 'stories',
 'street',
 'strong',
 'structure',
 'subscriber',
 'subscriptions',
 'succeeds',
 'success',
 'support',
 'supreme',
 'symbol',
 'takes',
 'talk',
 'target',
 'targets',
 'tech',
 'techcrunch',
 'technology',
 'terms',
 'tests',
 'thacher',
 'thanks',
 'thing',
 'things',
 'think',
 'thursday',
 'ticker',
 'time',
 'tops',
 'total',
 'trade',
 'traded',
 'trader',
 'trading',
 'trail',
 'trick',
 'trucking',
 'trump',
 'turn',
 'underwriters',
 'unicorn',
 'unicorns',
 'united',
 'unity',
 'unveils',
 'upcoming',
 'update',
 'updates',
 'ups',
 'upsized',
 'usd',
 'usdnum_',
 'usdnum_b',
 'user',
 'users',
 'valiant',
 'valley',
 'valuation',
 'value',
 'valued',
 'values',
 'valuing',
 'vapor',
 'vc',
 'vcs',
 'vendor',
 'venture',
 'view',
 'views',
 'visit',
 'volatility',
 'wall',
 'want',
 'wants',
 'warner',
 'warns',
 'watch',
 'watched',
 'web',
 'week',
 'win',
 'winner',
 'winners',
 'worth',
 'wsj',
 'year',
 'years',
 'york',
 'zscaler']

In [88]:
pd.DataFrame.from_dict(vectorizer.vocabulary_, orient='index').sort_values(by=0, ascending=False).head()

           0
zscaler  568
york     567
years    566
year     565
wsj      564

In [89]:
dtm = vectorizer.transform(text_data)
dtm

<367x569 sparse matrix of type '<class 'numpy.int64'>'
	with 1895 stored elements in Compressed Sparse Row format>

In [90]:
Text_Features = pd.DataFrame(dtm.toarray(), columns=vectorizer.get_feature_names())
Text_Features.shape

(367, 569)

In [99]:
murali_scores = pd.read_excel('testdata_sentiment_score_final.xlsx')
alam_scores = pd.read_csv('DocusignDropbox-With-Sentiment.csv')

In [120]:
murali_scores.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 367 entries, 0 to 366
Data columns (total 8 columns):
Headline         367 non-null object
Source           367 non-null object
Date             367 non-null object
Word Count       367 non-null int64
Company          367 non-null object
PositiveScore    367 non-null float64
NegativeScore    367 non-null int64
Ticker           367 non-null object
dtypes: float64(1), int64(2), object(5)
memory usage: 25.8+ KB

In [163]:
murali_scores['Ticker'] = murali_scores['Company'].map(company_ticker)
alam_scores['Ticker'] = alam_scores['Company'].map(company_ticker)

In [164]:
df = pd.merge(headlines, murali_scores[['PositiveScore', 'NegativeScore']], left_index=True, right_index=True)

In [166]:
df2 = pd.merge(df, alam_scores[['neutral', 'weakneg', 'weakpos', 'strongpos', 'strongneg']], left_index=True, right_index=True)

In [167]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 13 columns):
Headline         367 non-null object
Source           367 non-null object
Date             367 non-null object
Word Count       367 non-null int64
Company          367 non-null object
Ticker           367 non-null object
PositiveScore    367 non-null float64
NegativeScore    367 non-null int64
neutral          367 non-null int64
weakneg          367 non-null int64
weakpos          367 non-null int64
strongpos        367 non-null int64
strongneg        367 non-null int64
dtypes: float64(1), int64(7), object(5)
memory usage: 37.4+ KB

In [185]:
df3 = pd.merge(df2, ipo_info[['Ticker', 'Label']], on='Ticker', how='outer')
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 368 entries, 0 to 367
Data columns (total 14 columns):
Headline         367 non-null object
Source           367 non-null object
Date             367 non-null object
Word Count       367 non-null float64
Company          367 non-null object
Ticker           368 non-null object
PositiveScore    367 non-null float64
NegativeScore    367 non-null float64
neutral          367 non-null float64
weakneg          367 non-null float64
weakpos          367 non-null float64
strongpos        367 non-null float64
strongneg        367 non-null float64
Label            300 non-null object
dtypes: float64(8), object(6)
memory usage: 43.1+ KB

In [182]:
#df3 = df3[df3['Label'].notnull()]

In [186]:
df3.head()

,Headline,Source,Date,Word Count,Company,Ticker,PositiveScore,NegativeScore,neutral,weakneg,weakpos,strongpos,strongneg,Label
0,*Docusign Files for IPO,Dow Jones Institutional News,3/28/18,109.0,Docusign,DOC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,*DocuSign Inc. IPO Offering 16M Shares at $24-...,Dow Jones Institutional News,4/17/18,27.0,Docusign,DOC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,*DocuSign Now Sees 16M-Share IPO Pricing at $2...,Dow Jones Institutional News,4/25/18,71.0,Docusign,DOC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,*DocuSign Updates IPO Filing,Dow Jones Institutional News,4/3/18,60.0,Docusign,DOC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,06:32 EDT Docusign IPO range raised to $26.00-...,Theflyonthewall.com,4/25/18,67.0,Docusign,DOC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [187]:
df3.to_csv('new_features_data.csv')